services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "13050:13050"
    volumes:
      - .:/app
      - /app/node_modules
  ui:
    build: ui
    volumes:
      - ./ui:/src
    ports:
      - "5173:5173"
