name: Firestore backup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: 'github-actions@build-tridnguyen-com.iam.gserviceaccount.com'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: 'build-tridnguyen-com'

      - name: Backup
        run: |-
          gcloud components install beta
          gcloud beta firestore export gs://build-tridnguyen-com-firestore-backups

