name: Firestore backup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2

      - name: Backup
        run: |-
          gcloud components install beta
          gcloud beta firestore export gs://build-tridnguyen-com-firestore-backups

