name: Cloud Run

on: push

# if needs to run on PR, conside using (https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662)
# on:
#   push:
#     branches:
#     - master
#   pull_request:
#     branches:
#     - master


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: credentials.json

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: Setup auth
        run: echo -n ${{ secrets.SA_KEY_DEV_BASE64 }} | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Test
        run: npm t

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    env:
      PROJECT_ID: build-tridnguyen-com
      RUN_REGION: us-central1
      SERVICE_NAME: lists

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: 'github-actions@build-tridnguyen-com.iam.gserviceaccount.com'
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: 'build-tridnguyen-com'

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
