name: Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  dev:
    name: Deploy to dev
    runs-on: ubuntu-latest

    env:
      REGION: us-central1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_KEY_DEV }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: gcloud info
        run: 'gcloud info'

      # Ideally, should set ingress-settings to "internal-only", but
      # that doesn't seem to be working
      # https://stackoverflow.com/questions/60321764/
      - name: apiToFirestore
        env:
          FUNCTION_NAME: lists-migrate-api-to-firestore
          ENTRY_POINT: apiToFirestore
          SCHEDULER_JOB_NAME: lists-migrate-api-to-firestore-trigger
          SCHEDULE: 30 19 * * *
        run: |-
          gcloud functions deploy $FUNCTION_NAME \
            --entry-point=$ENTRY_POINT \
            --allow-unauthenticated \
            --region "$REGION" \
            --runtime nodejs16 \
            --ingress-settings=all \
            --trigger-http
          # gcloud scheduler jobs update http $SCHEDULER_JOB_NAME \
          #   --schedule="$SCHEDULE" \
          #   --uri="$(gcloud functions describe $FUNCTION_NAME --format='value(httpsTrigger.url)')"
