name: Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  dev:
    name: Deploy to dev
    runs-on: ubuntu-latest

    env:
      REGION: us-central1
      FUNCTION_NAME: lists-migrate-api-to-firestore

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_KEY_DEV }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: gcloud info
        run: 'gcloud info'

      # Ideally, should set ingress-settings to "internal-only", but
      # that doesn't seem to be working
      # https://stackoverflow.com/questions/60321764/
      - name: Deploy apiToFirestore
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: nodejs16
          entry_point: apiToFirestore
          ingress_settings: ALLOW_ALL

      # - name: Scheduler
      #   env:
      #     SCHEDULER_JOB_NAME: lists-migrate-api-to-firestore-trigger
      #     SCHEDULE: 30 19 * * *
      #   run: |-
      #     gcloud scheduler jobs update http $SCHEDULER_JOB_NAME \
      #       --schedule="$SCHEDULE" \
      #       --uri="$(gcloud functions describe $FUNCTION_NAME --format='value(httpsTrigger.url)')"
