name: UI CI/CD

on: push

defaults:
  run:
    working-directory: ui

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci -f  # force because of svelte 5 peer dep - remove when it's fixed

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build
