name: UI CI/CD

on:
  push:
    # only trigger when changes are made to the UI directory
    paths:
      - 'ui/**'
      - '.github/workflows/deploy-ui.yml'

defaults:
  run:
    working-directory: ui

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          PUBLIC_API_URL: 'https://lists.cloud.tridnguyen.com'
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'ui/build/'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Pages
        id: deployment
        uses: actions/deploy-pages@v4
